env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: &rules
  prettier/prettier:
    - error
    - singleQuote: true
      semi: false
      trailingComma: all
      bracketSpacing: false
      printWidth: 120
      arrowParens: avoid
  indent:
    - 'off'
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  object-curly-spacing: 'off'
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  react/jsx-filename-extension:
    - 0
    - extensions:
        - ".js"
        - ".jsx"
  react/react-in-jsx-scope: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  import/extensions: 0
  react/jsx-props-no-spreading: 0
  react/state-in-constructor: 0
  no-shadow: 0
  '@typescript-eslint/no-shadow': error
  react/forbid-prop-types:
    - 0
  no-underscore-dangle:
    - 0
  react/prop-types:
    - 0
  jsx-a11y/label-has-for:
    - 0
  jsx-a11y/anchor-is-valid:
    - 1
    - aspects:
        - invalidHref
        - preferButton
  jsx-a11y/no-autofocus:
    - 0
  camelcase:
    - 0
  no-return-assign: 'off'
  no-param-reassign: 'off'
  no-nested-ternary: 'off'
  no-use-before-define: 0
  class-methods-use-this: 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-unused-vars': 0
  arrow-parens: 'off'
  max-classes-per-file: 0
  react-hooks/exhaustive-deps: error
  '@typescript-eslint/ban-ts-comment':
    - 'warn'
    - 'ts-ignore': 'allow-with-description'
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    extends:
      - eslint:recommended
      - airbnb
      - plugin:react/recommended
      - plugin:prettier/recommended
      - prettier/react
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
      - plugin:import/typescript
    plugins:
      - prettier
      - react-hooks
      - "@typescript-eslint"
    rules: *rules
