version: '3'

services:
  backend:
    build: backend
    ports:
      - 8081:8081
      - 8080:8080

  datenbank:
    build: notification/db-docker
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=world

  notification:
    depends_on:
      - datenbank
      - backend
    build: notification
    ports:
      - 8082:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://datenbank:5432/world
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=docker
      - sensors.backend.url=http://backend:8080

  frontend:
    depends_on:
      - backend
      - notification
    build: frontend
    ports:
      - 3000:3000
