version: '3'

services:
  backend:
    build: backend
    ports:
      - 8081:8081
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://smartaqnet-worker1-clone.dmz.teco.edu:5432/sensorthings?currentSchema=public
      - spring.datasource.username=sensorthings
      - spring.datasource.password=ChangeMe

  datenbank:
    build: notification/db-docker
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=world

  notification:
    depends_on:
      - datenbank
      - backend
    build: notification
    ports:
      - 8082:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://datenbank:5432/world
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=docker
      - sensors.backend.url=http://backend:8081
      - MAIL_PASSWORD=cKqp4Wa83pLddBv
      - MAIL_USERNAME=sensornotificationsystemPSE@gmail.com
      - MAIL_SMTP_HOST=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SOCKETFACTORY_PORT=587

  frontend:
    depends_on:
      - backend
      - notification
    build: frontend
    ports:
      - 3001:80
    environment:
      - API_BACKEND_URL=http://backend:8081
      - API_NOTIFICATION_URL=http://notification:8080
