version: '3'

services:
  backend:
    build: backend
    ports:
      - 8081:8081
      - 8080:8080

  datenbank:
    build: notification/db-docker

  notification:
    depends_on:
      - datenbank
    build: notification
    ports:
    - 8082:8080

  frontend:
    depends_on:
      - backend
      - notification
    build: frontend
    ports:
      - 3000:3000