package edu.teco.sensordatenbankmanagementsystem.exceptions;

/**
 * {@link ImageCantBeGeneratedException} is thrown when an image was attempted to be generated by the application,
 * but failed
 */
public class ImageCantBeGeneratedException extends RuntimeException{
}
